### ISSUE TITLE
[BUG] npm installation failed

### ISSUE THREAD

**Issue by yash1441** [djs-modules/notifier#1]
**Describe the bug**
Not able to install this npm package.

**To Reproduce**
1. `npm install @djs-module/notifier`

**Screenshots**
![image](https://user-images.githubusercontent.com/14055917/192696160-7d3595cf-6be1-4fa6-ab0b-69c1802abfa8.png)

**Information:**
 - NodeJS 16 & NodeJS 18

**Comment by unqxl** [comment]
**Thank you for the information you provided. The bug will be corrected in an upcoming urgent update!**

**Comment by unqxl** [comment]
**Fixed in eab2b42c0c0847017a4268f09d6dc6858479b41a!**
